[phases.setup]
nixPkgs = ['python39', 'tesseract4']

[phases.install]
cmds = [
  'pip install -r requirements.txt'
]

[phases.build]
cmds = [
  'echo "Checking Tesseract installation..."',
  'tesseract --version || echo "Tesseract not found"'
]

[start]
cmd = 'python bridge_runner.py'
